spring.application.name=bookspace

#dataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}?serverTimezone=UTC
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

#mybtais
#mappers
#mybatis.mapper-locations=classpath:mappers/boardMapper.xml
mybatis.mapper-locations=classpath:mappers/*.xml

#type as
mybatis.type-aliases-package=com.bookspace.mvc.model.dto

mybatis.configuration.map-underscore-to-camel-case=true

#file size default 1MB
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=20MB

